### ISSUE TITLE
Version 4 beta

### ISSUE THREAD

**Issue by hbaghour** [goautodial/v4-ce#3]
Hi,

We are working on a new version of our CRM, and we are planing a full integration of the new version of GoAutoDial with the new CRM. So i'd like to know if it's already possible to download a beta version, so we can work with the integration and make some customizations while we are waiting for the stable version of the v4?

Btw, thank you very much for all the time and effort spent on this project!

**Comment by demianb** [comment]
Hey guys,

Just a little bit of delay due to some bugs on the reports plus some client customizations. Other than that, we're around 90% done on the MariaDB/MySQL prepared statements conversion. So this will definitely happen this April 2018.
